import ThemeWrapperProvider from "@/app/components/layout/Wrapper";
import "@/app/globals.css";

export const metadata = {
  title: "PPTI QODR LOGIN",
  description: "Generated by Arsdev998",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="antialiased" suppressHydrationWarning={true}>
        <ThemeWrapperProvider>{children}</ThemeWrapperProvider>
      </body>
    </html>
  );
}
